# Generated by Django 4.2.2 on 2023-06-21 22:01

import code_api.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', code_api.models.user.AppUserManager()),
            ],
        ),
    ]
