# Generated by Django 4.2.2 on 2023-06-16 20:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('code_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='lastname',
            new_name='admin_lastname',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='name',
            new_name='admin_name',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='password',
            new_name='admin_password',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='language',
            new_name='community_language',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='question_title',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='birthday',
            new_name='user_birthday',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='community',
            new_name='user_community',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='user_image',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='user_lastname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='user_nickname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='postulation',
            new_name='user_postulation',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='community',
            name='description',
        ),
        migrations.RemoveField(
            model_name='community',
            name='name',
        ),
        migrations.RemoveField(
            model_name='community',
            name='users',
        ),
        migrations.RemoveField(
            model_name='language',
            name='name',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='post',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.RemoveField(
            model_name='news',
            name='date',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
        migrations.RemoveField(
            model_name='news',
            name='link',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='createdate',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.RemoveField(
            model_name='question',
            name='description',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
        migrations.AddField(
            model_name='admin',
            name='admin_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='admin_email',
            field=models.EmailField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='admin_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_description',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_question',
            field=models.ForeignKey(default='', limit_choices_to={'my_foreign_key__isnull': True}, on_delete=django.db.models.deletion.CASCADE, to='code_api.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_user',
            field=models.ForeignKey(default='', limit_choices_to={'my_foreign_key__isnull': True}, on_delete=django.db.models.deletion.CASCADE, to='code_api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_description',
            field=models.TextField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_post',
            field=models.ForeignKey(default='', limit_choices_to={'my_foreign_key__isnull': True}, on_delete=django.db.models.deletion.CASCADE, to='code_api.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_user',
            field=models.ForeignKey(default='', limit_choices_to={'my_foreign_key__isnull': True}, on_delete=django.db.models.deletion.CASCADE, to='code_api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='community_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='community',
            name='community_description',
            field=models.TextField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='community_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='language_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likes',
            name='likes_post',
            field=models.ForeignKey(default='', limit_choices_to={'my_foreign_key__isnull': True}, on_delete=django.db.models.deletion.CASCADE, to='code_api.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likes',
            name='likes_user',
            field=models.ForeignKey(default='', limit_choices_to={'my_foreign_key__isnull': True}, on_delete=django.db.models.deletion.CASCADE, to='code_api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='news_author',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='news_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='news',
            name='news_description',
            field=models.TextField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='news_link',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='news_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='post_description',
            field=models.TextField(default='', max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_user',
            field=models.ForeignKey(default='', limit_choices_to={'my_foreign_key__isnull': True}, on_delete=django.db.models.deletion.CASCADE, to='code_api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='question',
            name='question_description',
            field=models.TextField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_user',
            field=models.ForeignKey(default='', limit_choices_to={'my_foreign_key__isnull': True}, on_delete=django.db.models.deletion.CASCADE, to='code_api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_language',
            field=models.ManyToManyField(to='code_api.language'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_password',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_premium',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='news_category',
            field=models.ManyToManyField(to='code_api.category'),
        ),
    ]
