# Generated by Django 4.2.2 on 2023-06-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_api', '0002_alter_appuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
