# Generated by Django 4.2.2 on 2023-06-22 01:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('code_api', '0003_appuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextras',
            name='created',
        ),
        migrations.RemoveField(
            model_name='userextras',
            name='modified',
        ),
        migrations.AddField(
            model_name='appuser',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
