# Generated by Django 4.2.2 on 2023-06-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_api', '0004_rename_user_name_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='image',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
