# Generated by Django 4.2.2 on 2023-06-22 18:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_api', '0004_remove_userextras_created_remove_userextras_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextras',
            name='user_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
