# Generated by Django 4.2.2 on 2023-06-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_api', '0004_alter_usercomplement_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='usercomplement',
            name='user_image',
            field=models.CharField(blank=True),
        ),
    ]
