# Generated by Django 4.2.2 on 2023-06-23 19:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_api', '0007_alter_userextras_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextras',
            name='user_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
