# Generated by Django 4.2.2 on 2023-07-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_api', '0007_usercomplement_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comments',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
