# Generated by Django 4.2.2 on 2023-07-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_api', '0008_answer_is_delete_comments_is_delete_post_is_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomplement',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
