# Generated by Django 4.2.2 on 2023-06-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_api', '0008_post_likes_alter_post_user_delete_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_post', to='code_api.user'),
        ),
    ]
