# Generated by Django 4.2.2 on 2023-06-22 11:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_api', '0009_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
