# Generated by Django 4.2.2 on 2023-07-05 16:34

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraccount_is_delete'),
        ('code_api', '0010_community_is_delete_news_is_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('review', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('comments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
