# Generated by Django 4.2.2 on 2023-07-06 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_api', '0011_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='review',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.IntegerField()),
                ('comment', models.CharField()),
                ('is_delete', models.BooleanField(default=False)),
                ('reviews_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_api.reviews')),
            ],
        ),
    ]
