# Generated by Django 4.2.2 on 2023-06-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_api', '0001_initial'),
    ]

    operations = [
    ]
