# Generated by Django 4.2.2 on 2023-06-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_api', '0002_auto_20230614_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('user_checkout', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('password', models.CharField()),
                ('nickname', models.CharField()),
                ('lastname', models.CharField()),
                ('language', models.CharField()),
                ('birthday', models.DateField()),
                ('postulation', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
