# Generated by Django 4.2.2 on 2023-06-16 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_api', '0003_rename_admin_created_admin_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='name',
        ),
    ]
