# Generated by Django 4.2.2 on 2023-06-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_api', '0004_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('author', models.CharField()),
                ('category', models.CharField()),
                ('link', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='community',
            name='user_checkout',
        ),
        migrations.RemoveField(
            model_name='language',
            name='user_checkout',
        ),
        migrations.AddField(
            model_name='community',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='community',
            name='language',
            field=models.ManyToManyField(to='code_api.language'),
        ),
        migrations.AddField(
            model_name='community',
            name='users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='community',
            field=models.ManyToManyField(default=1, to='code_api.community'),
        ),
    ]
