# Generated by Django 4.2.2 on 2023-06-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_api', '0004_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='user_checkout',
        ),
        migrations.RemoveField(
            model_name='language',
            name='user_checkout',
        ),
        migrations.AddField(
            model_name='user',
            name='community',
            field=models.ManyToManyField(to='code_api.community'),
        ),
    ]
