# Generated by Django 4.2.2 on 2023-06-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_api', '0005_news_remove_community_user_checkout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
