# Generated by Django 4.2.2 on 2023-07-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
