// types.ts
export const GET_ALL_POST = "GET_ALL_POST";
export const GET_BY_NAME = "GET_BY_NAME";
export const ADD_POST = "ADD_POST";
export const FILTER_ZA = "FILTER_ZA";
export const FILTER_AZ = "FILTER_AZ";
export const GET_ALL_LANGUAGES = "GET_ALL_LANGUAGES";
export const POST_USER = "POST_USER";
export const FILTER_ABC = "FILTER_ABC";
export const FILTER_PUBLICATIONS = "FILTER_PUBLICATIONS";
export const SEARCH = "SEARCH";
export const GET_COMMUNITY = "GET_COMMUNITY";
export const POST_COMMUNITY = "POST_COMMUNITY";
export const GET_ALL_COMMUNITIES = "GET_ALL_COMMUNITIES";
export const ADD_NEWS = "ADD_NEWS";
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_NEWS = "GET_NEWS";
export const USERS = "USERS";
export const GETPOSTID = "GETPOSTID";
export const FAKE_LOGGIN = "FAKE_LOGGIN";
export const FAKE_BUTTON = "FAKE_BUTTON";
export const GET_USER_EXTRA = "GET_USER_EXTRA";


export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL';
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'PASSWORD_RESET_CONFIRM_SUCCESS';
export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS';
export const GOOGLE_AUTH_FAIL = 'GOOGLE_AUTH_FAIL';
export const FACEBOOK_AUTH_SUCCESS = 'FACEBOOK_AUTH_SUCCESS';
export const FACEBOOK_AUTH_FAIL = 'FACEBOOK_AUTH_FAIL';
export const LOGOUT = 'LOGOUT';

