# Generated by Django 4.2.2 on 2023-06-12 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_delete_mimodelo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
